# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20151202_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marked_as_answer',
            field=models.BooleanField(default=False, verbose_name='Marked as Answer'),
        ),
    ]
